/****************************************************************************
 *
 * CRI Middleware SDK
 *
 * Copyright (c) 2008 CRI Middleware, Inc. All rights reserved.
 *
 * Use, modification and distribution are subject to the CRI Script Software
 * License, Version 1.0(see accompanying file "CriScript_License_1_0.txt" or
 * copy at www.criscript.com/trac/wiki/CRI%20Script%20Software%20License%201.0 ).
 *
 *
 * Library  : CRIScript
 * Module   : CIL op code definitions
 * File     : cilOpcode.cpp
 * Date     : 
 * Version  : 
 *
 ****************************************************************************/

/***************************************************************************
 *      Include file
 ***************************************************************************/
#include "stdafx.h"
#include "criscript.h"
namespace cri {

/***************************************************************************
 *      Variables
 ***************************************************************************/

/***************************************************************************
 * Ope code table
 ***************************************************************************/	

OPCODE_TABLEENTRY g_Opecode[] = {
	OPDEF(CEE_NOP,                        "nop",              POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x00,    NEXT)
	OPDEF(CEE_BREAK,                      "break",            POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x01,    BREAK)
	OPDEF(CEE_LDARG_0,                    "ldarg.0",          POP_0,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x02,    NEXT)
	OPDEF(CEE_LDARG_1,                    "ldarg.1",          POP_0,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x03,    NEXT)
	OPDEF(CEE_LDARG_2,                    "ldarg.2",          POP_0,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x04,    NEXT)
	OPDEF(CEE_LDARG_3,                    "ldarg.3",          POP_0,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x05,    NEXT)
	OPDEF(CEE_LDLOC_0,                    "ldloc.0",          POP_0,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x06,    NEXT)
	OPDEF(CEE_LDLOC_1,                    "ldloc.1",          POP_0,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x07,    NEXT)
	OPDEF(CEE_LDLOC_2,                    "ldloc.2",          POP_0,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x08,    NEXT)
	OPDEF(CEE_LDLOC_3,                    "ldloc.3",          POP_0,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x09,    NEXT)
	OPDEF(CEE_STLOC_0,                    "stloc.0",          POP_1,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x0A,    NEXT)
	OPDEF(CEE_STLOC_1,                    "stloc.1",          POP_1,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x0B,    NEXT)
	OPDEF(CEE_STLOC_2,                    "stloc.2",          POP_1,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x0C,    NEXT)
	OPDEF(CEE_STLOC_3,                    "stloc.3",          POP_1,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x0D,    NEXT)
	OPDEF(CEE_LDARG_S,                    "ldarg.s",          POP_0,               PUSH_1,       OPERAND_PARAMS_SHORT_INLINE_VAR,     IMACRO,      1,  0xFF,    0x0E,    NEXT)
	OPDEF(CEE_LDARGA_S,                   "ldarga.s",         POP_0,               PUSH_I,       OPERAND_PARAMS_SHORT_INLINE_VAR,     IMACRO,      1,  0xFF,    0x0F,    NEXT)
	OPDEF(CEE_STARG_S,                    "starg.s",          POP_1,               PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_VAR,     IMACRO,      1,  0xFF,    0x10,    NEXT)
	OPDEF(CEE_LDLOC_S,                    "ldloc.s",          POP_0,               PUSH_1,       OPERAND_PARAMS_SHORT_INLINE_VAR,     IMACRO,      1,  0xFF,    0x11,    NEXT)
	OPDEF(CEE_LDLOCA_S,                   "ldloca.s",         POP_0,               PUSH_I,       OPERAND_PARAMS_SHORT_INLINE_VAR,     IMACRO,      1,  0xFF,    0x12,    NEXT)
	OPDEF(CEE_STLOC_S,                    "stloc.s",          POP_1,               PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_VAR,     IMACRO,      1,  0xFF,    0x13,    NEXT)
	OPDEF(CEE_LDNULL,                     "ldnull",           POP_0,               PUSH_REF,     OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x14,    NEXT)
	OPDEF(CEE_LDC_I4_M1,                  "ldc.i4.m1",        POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x15,    NEXT)
	OPDEF(CEE_LDC_I4_0,                   "ldc.i4.0",         POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x16,    NEXT)
	OPDEF(CEE_LDC_I4_1,                   "ldc.i4.1",         POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x17,    NEXT)
	OPDEF(CEE_LDC_I4_2,                   "ldc.i4.2",         POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x18,    NEXT)
	OPDEF(CEE_LDC_I4_3,                   "ldc.i4.3",         POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x19,    NEXT)
	OPDEF(CEE_LDC_I4_4,                   "ldc.i4.4",         POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x1A,    NEXT)
	OPDEF(CEE_LDC_I4_5,                   "ldc.i4.5",         POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x1B,    NEXT)
	OPDEF(CEE_LDC_I4_6,                   "ldc.i4.6",         POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x1C,    NEXT)
	OPDEF(CEE_LDC_I4_7,                   "ldc.i4.7",         POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x1D,    NEXT)
	OPDEF(CEE_LDC_I4_8,                   "ldc.i4.8",         POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IMACRO,      1,  0xFF,    0x1E,    NEXT)
	OPDEF(CEE_LDC_I4_S,                   "ldc.i4.s",         POP_0,               PUSH_I,       OPERAND_PARAMS_SHORT_INLINE_I,       IMACRO,      1,  0xFF,    0x1F,    NEXT)
	OPDEF(CEE_LDC_I4,                     "ldc.i4",           POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_I,            IPRIMITIVE,  1,  0xFF,    0x20,    NEXT)
	OPDEF(CEE_LDC_I8,                     "ldc.i8",           POP_0,               PUSH_I8,      OPERAND_PARAMS_INLINE_I8,           IPRIMITIVE,  1,  0xFF,    0x21,    NEXT)
	OPDEF(CEE_LDC_R4,                     "ldc.r4",           POP_0,               PUSH_R4,      OPERAND_PARAMS_SHORT_INLINE_R,       IPRIMITIVE,  1,  0xFF,    0x22,    NEXT)
	OPDEF(CEE_LDC_R8,                     "ldc.r8",           POP_0,               PUSH_R8,      OPERAND_PARAMS_INLINE_R,            IPRIMITIVE,  1,  0xFF,    0x23,    NEXT)
	OPDEF(CEE_UNUSED49,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x24,    NEXT)
	OPDEF(CEE_DUP,                        "dup",              POP_1,               PUSH_1+PUSH_1, OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x25,    NEXT)
	OPDEF(CEE_POP,                        "pop",              POP_1,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x26,    NEXT)
	OPDEF(CEE_JMP,                        "jmp",              POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_METHOD,       IPRIMITIVE,  1,  0xFF,    0x27,    CALL)
	//OPDEF(CEE_CALL,                       "call",             POP_VAR,             PUSH_VAR,     OPERAND_PARAMS_INLINE_METHOD,       IPRIMITIVE,  1,  0xFF,    0x28,    CALL)
	//OPDEF(CEE_CALLI,                      "calli",            POP_VAR,             PUSH_VAR,     OPERAND_PARAMS_INLINE_SIG,          IPRIMITIVE,  1,  0xFF,    0x29,    CALL)
	//Push 1 return value
	OPDEF(CEE_CALL,                       "call",             POP_0,               PUSH_1,     OPERAND_PARAMS_INLINE_METHOD,       IPRIMITIVE,  1,  0xFF,    0x28,    CALL)
	OPDEF(CEE_CALLI,                      "calli",            POP_0,               PUSH_1,     OPERAND_PARAMS_INLINE_SIG,          IPRIMITIVE,  1,  0xFF,    0x29,    CALL)
	//OPDEF(CEE_RET,                        "ret",              POP_VAR,           PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x2A,    RETURN)
	//Push a return value
	OPDEF(CEE_RET,                        "ret",              POP_VAR,             PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x2A,    RETURN)
	OPDEF(CEE_BR_S,                       "br.s",             POP_0,               PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x2B,    BRANCH)
	OPDEF(CEE_BRFALSE_S,                  "brfalse.s",        POP_I,               PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x2C,    COND_BRANCH)
	OPDEF(CEE_BRTRUE_S,                   "brtrue.s",         POP_I,               PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x2D,    COND_BRANCH)
	OPDEF(CEE_BEQ_S,                      "beq.s",            POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x2E,    COND_BRANCH)
	OPDEF(CEE_BGE_S,                      "bge.s",            POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x2F,    COND_BRANCH)
	OPDEF(CEE_BGT_S,                      "bgt.s",            POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x30,    COND_BRANCH)
	OPDEF(CEE_BLE_S,                      "ble.s",            POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x31,    COND_BRANCH)
	OPDEF(CEE_BLT_S,                      "blt.s",            POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x32,    COND_BRANCH)
	OPDEF(CEE_BNE_UN_S,                   "bne.un.s",         POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x33,    COND_BRANCH)
	OPDEF(CEE_EXT_BNGE_S,                 "bnge.ex.s",          POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x34,    COND_BRANCH)
	OPDEF(CEE_EXT_BNGT_S,                 "bngt.ex.s",          POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x35,    COND_BRANCH)
	OPDEF(CEE_EXT_BNLE_S,                 "bnle.ex.s",          POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x36,    COND_BRANCH)
	OPDEF(CEE_EXT_BNLT_S,                 "bnlt.ex.s",          POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x37,    COND_BRANCH)
	//OPDEF(CEE_BGE_UN_S,                   "bge.un.s",         POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x34,    COND_BRANCH)
	//OPDEF(CEE_BGT_UN_S,                   "bgt.un.s",         POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x35,    COND_BRANCH)
	//OPDEF(CEE_BLE_UN_S,                   "ble.un.s",         POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x36,    COND_BRANCH)
	//OPDEF(CEE_BLT_UN_S,                   "blt.un.s",         POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IMACRO,      1,  0xFF,    0x37,    COND_BRANCH)
	OPDEF(CEE_BR,                         "br",               POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IPRIMITIVE,  1,  0xFF,    0x38,    BRANCH)
	OPDEF(CEE_BRFALSE,                    "brfalse",          POP_I,               PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IPRIMITIVE,  1,  0xFF,    0x39,    COND_BRANCH)
	OPDEF(CEE_BRTRUE,                     "brtrue",           POP_I,               PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IPRIMITIVE,  1,  0xFF,    0x3A,    COND_BRANCH)
	OPDEF(CEE_BEQ,                        "beq",              POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x3B,    COND_BRANCH)
	OPDEF(CEE_BGE,                        "bge",              POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x3C,    COND_BRANCH)
	OPDEF(CEE_BGT,                        "bgt",              POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x3D,    COND_BRANCH)
	OPDEF(CEE_BLE,                        "ble",              POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x3E,    COND_BRANCH)
	OPDEF(CEE_BLT,                        "blt",              POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x3F,    COND_BRANCH)
	OPDEF(CEE_BNE_UN,                     "bne.un",           POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x40,    COND_BRANCH)
	OPDEF(CEE_EXT_BNGE,                   "bnge.ex",          POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x41,    COND_BRANCH)
	OPDEF(CEE_EXT_BNGT,                   "bngt.ex",          POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x42,    COND_BRANCH)
	OPDEF(CEE_EXT_BNLE,                   "bnle.ex",          POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x43,    COND_BRANCH)
	OPDEF(CEE_EXT_BNLT,                   "bnlt.ex",          POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x44,    COND_BRANCH)
	//OPDEF(CEE_BGE_UN,                     "bge.un",           POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x41,    COND_BRANCH)
	//OPDEF(CEE_BGT_UN,                     "bgt.un",           POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x42,    COND_BRANCH)
	//OPDEF(CEE_BLE_UN,                     "ble.un",           POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x43,    COND_BRANCH)
	//OPDEF(CEE_BLT_UN,                     "blt.un",           POP_1+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IMACRO,      1,  0xFF,    0x44,    COND_BRANCH)
	OPDEF(CEE_SWITCH,                     "switch",           POP_I,               PUSH_0,       OPERAND_PARAMS_INLINE_SWITCH,       IPRIMITIVE,  1,  0xFF,    0x45,    COND_BRANCH)
	OPDEF(CEE_LDIND_I1,                   "ldind.i1",         POP_I,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x46,    NEXT)
	OPDEF(CEE_LDIND_U1,                   "ldind.u1",         POP_I,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x47,    NEXT)
	OPDEF(CEE_LDIND_I2,                   "ldind.i2",         POP_I,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x48,    NEXT)
	OPDEF(CEE_LDIND_U2,                   "ldind.u2",         POP_I,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x49,    NEXT)
	OPDEF(CEE_LDIND_I4,                   "ldind.i4",         POP_I,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x4A,    NEXT)
	OPDEF(CEE_LDIND_U4,                   "ldind.u4",         POP_I,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x4B,    NEXT)
	OPDEF(CEE_LDIND_I8,                   "ldind.i8",         POP_I,               PUSH_I8,      OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x4C,    NEXT)
	OPDEF(CEE_LDIND_I,                    "ldind.i",          POP_I,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x4D,    NEXT)
	OPDEF(CEE_LDIND_R4,                   "ldind.r4",         POP_I,               PUSH_R4,      OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x4E,    NEXT)
	OPDEF(CEE_LDIND_R8,                   "ldind.r8",         POP_I,               PUSH_R8,      OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x4F,    NEXT)
	OPDEF(CEE_LDIND_REF,                  "ldind.ref",        POP_I,               PUSH_REF,     OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x50,    NEXT)
	OPDEF(CEE_STIND_REF,                  "stind.ref",        POP_I+POP_I,         PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x51,    NEXT)
	OPDEF(CEE_STIND_I1,                   "stind.i1",         POP_I+POP_I,         PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x52,    NEXT)
	OPDEF(CEE_STIND_I2,                   "stind.i2",         POP_I+POP_I,         PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x53,    NEXT)
	OPDEF(CEE_STIND_I4,                   "stind.i4",         POP_I+POP_I,         PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x54,    NEXT)
	OPDEF(CEE_STIND_I8,                   "stind.i8",         POP_I+POP_I8,        PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x55,    NEXT)
	OPDEF(CEE_STIND_R4,                   "stind.r4",         POP_I+POP_R4,        PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x56,    NEXT)
	OPDEF(CEE_STIND_R8,                   "stind.r8",         POP_I+POP_R8,        PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x57,    NEXT)
	OPDEF(CEE_ADD,                        "add",              POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x58,    NEXT)
	OPDEF(CEE_SUB,                        "sub",              POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x59,    NEXT)
	OPDEF(CEE_MUL,                        "mul",              POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x5A,    NEXT)
	OPDEF(CEE_DIV,                        "div",              POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x5B,    NEXT)
	OPDEF(CEE_DIV_UN,                     "div.un",           POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x5C,    NEXT)
	OPDEF(CEE_REM,                        "rem",              POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x5D,    NEXT)
	OPDEF(CEE_REM_UN,                     "rem.un",           POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x5E,    NEXT)
	OPDEF(CEE_AND,                        "and",              POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x5F,    NEXT)
	OPDEF(CEE_OR,                         "or",               POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x60,    NEXT)
	OPDEF(CEE_XOR,                        "xor",              POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x61,    NEXT)
	OPDEF(CEE_SHL,                        "shl",              POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x62,    NEXT)
	OPDEF(CEE_SHR,                        "shr",              POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x63,    NEXT)
	OPDEF(CEE_SHR_UN,                     "shr.un",           POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x64,    NEXT)
	OPDEF(CEE_NEG,                        "neg",              POP_1,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x65,    NEXT)
	OPDEF(CEE_NOT,                        "not",              POP_1,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x66,    NEXT)
	OPDEF(CEE_CONV_I1,                    "conv.i1",          POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x67,    NEXT)
	OPDEF(CEE_CONV_I2,                    "conv.i2",          POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x68,    NEXT)
	OPDEF(CEE_CONV_I4,                    "conv.i4",          POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x69,    NEXT)
	OPDEF(CEE_CONV_I8,                    "conv.i8",          POP_1,               PUSH_I8,      OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x6A,    NEXT)
	OPDEF(CEE_CONV_R4,                    "conv.r4",          POP_1,               PUSH_R4,      OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x6B,    NEXT)
	OPDEF(CEE_CONV_R8,                    "conv.r8",          POP_1,               PUSH_R8,      OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x6C,    NEXT)
	OPDEF(CEE_CONV_U4,                    "conv.u4",          POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x6D,    NEXT)
	OPDEF(CEE_CONV_U8,                    "conv.u8",          POP_1,               PUSH_I8,      OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x6E,    NEXT)
	OPDEF(CEE_CALLVIRT,                   "callvirt",         POP_VAR,             PUSH_VAR,     OPERAND_PARAMS_INLINE_METHOD,       IOBJMODEL,   1,  0xFF,    0x6F,    CALL)
	OPDEF(CEE_CPOBJ,                      "cpobj",            POP_I+POP_I,         PUSH_0,       OPERAND_PARAMS_INLINE_TYPE,         IOBJMODEL,   1,  0xFF,    0x70,    NEXT)
	OPDEF(CEE_LDOBJ,                      "ldobj",            POP_I,               PUSH_1,       OPERAND_PARAMS_INLINE_TYPE,         IOBJMODEL,   1,  0xFF,    0x71,    NEXT)
	OPDEF(CEE_LDSTR,                      "ldstr",            POP_0,               PUSH_REF,     OPERAND_PARAMS_INLINE_STRING,       IOBJMODEL,   1,  0xFF,    0x72,    NEXT)
	OPDEF(CEE_NEWOBJ,                     "newobj",           POP_VAR,             PUSH_REF,     OPERAND_PARAMS_INLINE_METHOD,       IOBJMODEL,   1,  0xFF,    0x73,    CALL)
	OPDEF(CEE_CASTCLASS,                  "castclass",        POP_REF,             PUSH_REF,     OPERAND_PARAMS_INLINE_TYPE,         IOBJMODEL,   1,  0xFF,    0x74,    NEXT)
	OPDEF(CEE_ISINST,                     "isinst",           POP_REF,             PUSH_I,       OPERAND_PARAMS_INLINE_TYPE,         IOBJMODEL,   1,  0xFF,    0x75,    NEXT)
	OPDEF(CEE_CONV_R_UN,                  "conv.r.un",        POP_1,               PUSH_R8,      OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x76,    NEXT)
	OPDEF(CEE_UNUSED58,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x77,    NEXT)
	OPDEF(CEE_UNUSED1,                    "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x78,    NEXT)
	OPDEF(CEE_UNBOX,                      "unbox",            POP_REF,             PUSH_I,       OPERAND_PARAMS_INLINE_TYPE,         IPRIMITIVE,  1,  0xFF,    0x79,    NEXT)
	OPDEF(CEE_THROW,                      "throw",            POP_REF,             PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x7A,    THROW)
	OPDEF(CEE_LDFLD,                      "ldfld",            POP_REF,             PUSH_1,       OPERAND_PARAMS_INLINE_FIELD,        IOBJMODEL,   1,  0xFF,    0x7B,    NEXT)
	OPDEF(CEE_LDFLDA,                     "ldflda",           POP_REF,             PUSH_I,       OPERAND_PARAMS_INLINE_FIELD,        IOBJMODEL,   1,  0xFF,    0x7C,    NEXT)
	OPDEF(CEE_STFLD,                      "stfld",            POP_REF+POP_1,       PUSH_0,       OPERAND_PARAMS_INLINE_FIELD,        IOBJMODEL,   1,  0xFF,    0x7D,    NEXT)
	OPDEF(CEE_LDSFLD,                     "ldsfld",           POP_0,               PUSH_1,       OPERAND_PARAMS_INLINE_FIELD,        IOBJMODEL,   1,  0xFF,    0x7E,    NEXT)
	OPDEF(CEE_LDSFLDA,                    "ldsflda",          POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_FIELD,        IOBJMODEL,   1,  0xFF,    0x7F,    NEXT)
	OPDEF(CEE_STSFLD,                     "stsfld",           POP_1,               PUSH_0,       OPERAND_PARAMS_INLINE_FIELD,        IOBJMODEL,   1,  0xFF,    0x80,    NEXT)
	OPDEF(CEE_STOBJ,                      "stobj",            POP_I+POP_1,         PUSH_0,       OPERAND_PARAMS_INLINE_TYPE,         IPRIMITIVE,  1,  0xFF,    0x81,    NEXT)
	OPDEF(CEE_CONV_OVF_I1_UN,             "conv.ovf.i1.un",   POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x82,    NEXT)
	OPDEF(CEE_CONV_OVF_I2_UN,             "conv.ovf.i2.un",   POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x83,    NEXT)
	OPDEF(CEE_CONV_OVF_I4_UN,             "conv.ovf.i4.un",   POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x84,    NEXT)
	OPDEF(CEE_CONV_OVF_I8_UN,             "conv.ovf.i8.un",   POP_1,               PUSH_I8,      OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x85,    NEXT)
	OPDEF(CEE_CONV_OVF_U1_UN,             "conv.ovf.u1.un",   POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x86,    NEXT)
	OPDEF(CEE_CONV_OVF_U2_UN,             "conv.ovf.u2.un",   POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x87,    NEXT)
	OPDEF(CEE_CONV_OVF_U4_UN,             "conv.ovf.u4.un",   POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x88,    NEXT)
	OPDEF(CEE_CONV_OVF_U8_UN,             "conv.ovf.u8.un",   POP_1,               PUSH_I8,      OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x89,    NEXT)
	OPDEF(CEE_CONV_OVF_I_UN,              "conv.ovf.i.un",    POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x8A,    NEXT)
	OPDEF(CEE_CONV_OVF_U_UN,              "conv.ovf.u.un",    POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0x8B,    NEXT)
	OPDEF(CEE_BOX,                        "box",              POP_1,               PUSH_REF,     OPERAND_PARAMS_INLINE_TYPE,         IPRIMITIVE,  1,  0xFF,    0x8C,    NEXT)
	OPDEF(CEE_NEWARR,                     "newarr",           POP_I,               PUSH_REF,     OPERAND_PARAMS_INLINE_TYPE,         IOBJMODEL,   1,  0xFF,    0x8D,    NEXT)
	OPDEF(CEE_LDLEN,                      "ldlen",            POP_REF,             PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x8E,    NEXT)
	OPDEF(CEE_LDELEMA,                    "ldelema",          POP_REF+POP_I,       PUSH_I,       OPERAND_PARAMS_INLINE_TYPE,         IOBJMODEL,   1,  0xFF,    0x8F,    NEXT)
	OPDEF(CEE_LDELEM_I1,                  "ldelem.i1",        POP_REF+POP_I,       PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x90,    NEXT)
	OPDEF(CEE_LDELEM_U1,                  "ldelem.u1",        POP_REF+POP_I,       PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x91,    NEXT)
	OPDEF(CEE_LDELEM_I2,                  "ldelem.i2",        POP_REF+POP_I,       PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x92,    NEXT)
	OPDEF(CEE_LDELEM_U2,                  "ldelem.u2",        POP_REF+POP_I,       PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x93,    NEXT)
	OPDEF(CEE_LDELEM_I4,                  "ldelem.i4",        POP_REF+POP_I,       PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x94,    NEXT)
	OPDEF(CEE_LDELEM_U4,                  "ldelem.u4",        POP_REF+POP_I,       PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x95,    NEXT)
	OPDEF(CEE_LDELEM_I8,                  "ldelem.i8",        POP_REF+POP_I,       PUSH_I8,      OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x96,    NEXT)
	OPDEF(CEE_LDELEM_I,                   "ldelem.i",         POP_REF+POP_I,       PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x97,    NEXT)
	OPDEF(CEE_LDELEM_R4,                  "ldelem.r4",        POP_REF+POP_I,       PUSH_R4,      OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x98,    NEXT)
	OPDEF(CEE_LDELEM_R8,                  "ldelem.r8",        POP_REF+POP_I,       PUSH_R8,      OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x99,    NEXT)
	OPDEF(CEE_LDELEM_REF,                 "ldelem.ref",       POP_REF+POP_I,       PUSH_REF,     OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x9A,    NEXT)
	OPDEF(CEE_STELEM_I,                   "stelem.i",         POP_REF+POP_I+POP_I, PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x9B,    NEXT)
	OPDEF(CEE_STELEM_I1,                  "stelem.i1",        POP_REF+POP_I+POP_I, PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x9C,    NEXT)
	OPDEF(CEE_STELEM_I2,                  "stelem.i2",        POP_REF+POP_I+POP_I, PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x9D,    NEXT)
	OPDEF(CEE_STELEM_I4,                  "stelem.i4",        POP_REF+POP_I+POP_I, PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x9E,    NEXT)
	OPDEF(CEE_STELEM_I8,                  "stelem.i8",        POP_REF+POP_I+POP_I8,PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0x9F,    NEXT)
	OPDEF(CEE_STELEM_R4,                  "stelem.r4",        POP_REF+POP_I+POP_R4,PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0xA0,    NEXT)
	OPDEF(CEE_STELEM_R8,                  "stelem.r8",        POP_REF+POP_I+POP_R8,PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0xA1,    NEXT)
	OPDEF(CEE_STELEM_REF,                 "stelem.ref",       POP_REF+POP_I+POP_REF,PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   1,  0xFF,    0xA2,    NEXT)
	OPDEF(CEE_LDELEM,                     "ldelem",           POP_REF+POP_I,       PUSH_1,       OPERAND_PARAMS_INLINE_TYPE,         IOBJMODEL,   1,  0xFF,    0xA3,    NEXT)
	OPDEF(CEE_STELEM,                     "stelem",           POP_REF+POP_I+POP_1, PUSH_0,       OPERAND_PARAMS_INLINE_TYPE,         IOBJMODEL,   1,  0xFF,    0xA4,    NEXT)
	OPDEF(CEE_UNBOX_ANY,                  "unbox.any",        POP_REF,             PUSH_1,       OPERAND_PARAMS_INLINE_TYPE,         IOBJMODEL,   1,  0xFF,    0xA5,    NEXT)
	OPDEF(CEE_UNUSED5,                    "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xA6,    NEXT)
	OPDEF(CEE_UNUSED6,                    "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xA7,    NEXT)
	OPDEF(CEE_UNUSED7,                    "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xA8,    NEXT)
	OPDEF(CEE_UNUSED8,                    "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xA9,    NEXT)
	OPDEF(CEE_UNUSED9,                    "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xAA,    NEXT)
	OPDEF(CEE_UNUSED10,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xAB,    NEXT)
	OPDEF(CEE_UNUSED11,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xAC,    NEXT)
	OPDEF(CEE_UNUSED12,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xAD,    NEXT)
	OPDEF(CEE_UNUSED13,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xAE,    NEXT)
	OPDEF(CEE_UNUSED14,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xAF,    NEXT)
	OPDEF(CEE_UNUSED15,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xB0,    NEXT)
	OPDEF(CEE_UNUSED16,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xB1,    NEXT)
	OPDEF(CEE_UNUSED17,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xB2,    NEXT)
	OPDEF(CEE_CONV_OVF_I1,                "conv.ovf.i1",      POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xB3,    NEXT)
	OPDEF(CEE_CONV_OVF_U1,                "conv.ovf.u1",      POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xB4,    NEXT)
	OPDEF(CEE_CONV_OVF_I2,                "conv.ovf.i2",      POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xB5,    NEXT)
	OPDEF(CEE_CONV_OVF_U2,                "conv.ovf.u2",      POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xB6,    NEXT)
	OPDEF(CEE_CONV_OVF_I4,                "conv.ovf.i4",      POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xB7,    NEXT)
	OPDEF(CEE_CONV_OVF_U4,                "conv.ovf.u4",      POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xB8,    NEXT)
	OPDEF(CEE_CONV_OVF_I8,                "conv.ovf.i8",      POP_1,               PUSH_I8,      OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xB9,    NEXT)
	OPDEF(CEE_CONV_OVF_U8,                "conv.ovf.u8",      POP_1,               PUSH_I8,      OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xBA,    NEXT)
	OPDEF(CEE_UNUSED50,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xBB,    NEXT)
	OPDEF(CEE_UNUSED18,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xBC,    NEXT)
	OPDEF(CEE_UNUSED19,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xBD,    NEXT)
	OPDEF(CEE_UNUSED20,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xBE,    NEXT)
	OPDEF(CEE_UNUSED21,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xBF,    NEXT)
	OPDEF(CEE_UNUSED22,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xC0,    NEXT)
	OPDEF(CEE_UNUSED23,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xC1,    NEXT)
	OPDEF(CEE_REFANYVAL,                  "refanyval",        POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_TYPE,         IPRIMITIVE,  1,  0xFF,    0xC2,    NEXT)
	OPDEF(CEE_CKFINITE,                   "ckfinite",         POP_1,               PUSH_R8,      OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xC3,    NEXT)
	OPDEF(CEE_UNUSED24,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xC4,    NEXT)
	OPDEF(CEE_UNUSED25,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xC5,    NEXT)
	OPDEF(CEE_MKREFANY,                   "mkrefany",         POP_I,               PUSH_1,       OPERAND_PARAMS_INLINE_TYPE,         IPRIMITIVE,  1,  0xFF,    0xC6,    NEXT)
	OPDEF(CEE_UNUSED59,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xC7,    NEXT)
	OPDEF(CEE_UNUSED60,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xC8,    NEXT)
	OPDEF(CEE_UNUSED61,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xC9,    NEXT)
	OPDEF(CEE_UNUSED62,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xCA,    NEXT)
	OPDEF(CEE_UNUSED63,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xCB,    NEXT)
	OPDEF(CEE_UNUSED64,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xCC,    NEXT)
	OPDEF(CEE_UNUSED65,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xCD,    NEXT)
	OPDEF(CEE_UNUSED66,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xCE,    NEXT)
	OPDEF(CEE_UNUSED67,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xCF,    NEXT)
	OPDEF(CEE_LDTOKEN,                    "ldtoken",          POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_TOK,          IPRIMITIVE,  1,  0xFF,    0xD0,    NEXT)
	OPDEF(CEE_CONV_U2,                    "conv.u2",          POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xD1,    NEXT)
	OPDEF(CEE_CONV_U1,                    "conv.u1",          POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xD2,    NEXT)
	OPDEF(CEE_CONV_I,                     "conv.i",           POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xD3,    NEXT)
	OPDEF(CEE_CONV_OVF_I,                 "conv.ovf.i",       POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xD4,    NEXT)
	OPDEF(CEE_CONV_OVF_U,                 "conv.ovf.u",       POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xD5,    NEXT)
	OPDEF(CEE_ADD_OVF,                    "add.ovf",          POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xD6,    NEXT)
	OPDEF(CEE_ADD_OVF_UN,                 "add.ovf.un",       POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xD7,    NEXT)
	OPDEF(CEE_MUL_OVF,                    "mul.ovf",          POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xD8,    NEXT)
	OPDEF(CEE_MUL_OVF_UN,                 "mul.ovf.un",       POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xD9,    NEXT)
	OPDEF(CEE_SUB_OVF,                    "sub.ovf",          POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xDA,    NEXT)
	OPDEF(CEE_SUB_OVF_UN,                 "sub.ovf.un",       POP_1+POP_1,         PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xDB,    NEXT)
	OPDEF(CEE_ENDFINALLY,                 "endfinally",       POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xDC,    RETURN)
	OPDEF(CEE_LEAVE,                      "leave",            POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_BRTARGET,     IPRIMITIVE,  1,  0xFF,    0xDD,    BRANCH)
	OPDEF(CEE_LEAVE_S,                    "leave.s",          POP_0,               PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_BRTARGET,IPRIMITIVE,  1,  0xFF,    0xDE,    BRANCH)
	OPDEF(CEE_STIND_I,                    "stind.i",          POP_I+POP_I,         PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xDF,    NEXT)
	OPDEF(CEE_CONV_U,                     "conv.u",           POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xE0,    NEXT)
	OPDEF(CEE_UNUSED26,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xE1,    NEXT)
	OPDEF(CEE_UNUSED27,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xE2,    NEXT)
	OPDEF(CEE_UNUSED28,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xE3,    NEXT)
	OPDEF(CEE_UNUSED29,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xE4,    NEXT)
	OPDEF(CEE_UNUSED30,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xE5,    NEXT)
	OPDEF(CEE_UNUSED31,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xE6,    NEXT)
	OPDEF(CEE_UNUSED32,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xE7,    NEXT)
	OPDEF(CEE_UNUSED33,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xE8,    NEXT)
	OPDEF(CEE_UNUSED34,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xE9,    NEXT)
	OPDEF(CEE_UNUSED35,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xEA,    NEXT)
	OPDEF(CEE_UNUSED36,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xEB,    NEXT)
	OPDEF(CEE_UNUSED37,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xEC,    NEXT)
	OPDEF(CEE_EXT_INCSFLD,                "incsfld.ex",       POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_FIELD,        IPRIMITIVE,  1,  0xFF,    0xED,    NEXT)

	OPDEF(CEE_UNUSED39,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xEE,    NEXT)
	OPDEF(CEE_UNUSED40,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xEF,    NEXT)
	OPDEF(CEE_EXT_INC,                    "inc.ex",           POP_1,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xF0,    NEXT)
	OPDEF(CEE_EXT_DEC,                    "dec.ex",           POP_1,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xF1,    NEXT)
	OPDEF(CEE_EXT_CONV_B,                 "conv.b.ex",        POP_1,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xF2,    NEXT)
	OPDEF(CEE_EXT_ENTER,                  "enter.ex",         POP_I,               PUSH_0,       OPERAND_PARAMS_INLINE_I,            IPRIMITIVE,  1,  0xFF,    0xF3,    NEXT)
	OPDEF(CEE_EXT_LEAVE,                  "leave.ex",         POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xF4,    NEXT)
	OPDEF(CEE_EXT_CALLI,                  "calli.ex",         POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xF5,    NEXT)
	OPDEF(CEE_EXT_FINALLY,                "finally.ex",       POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  1,  0xFF,    0xF8,    META)
	OPDEF(CEE_EXT_STARGLIST_S,            "starglist.s",      POP_VAR,             PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_I,       IPRIMITIVE,  1,  0xFF,    0xF6,    NEXT)
	OPDEF(CEE_EXT_STARGLIST,              "starglist",        POP_VAR,             PUSH_0,       OPERAND_PARAMS_INLINE_I,			   IPRIMITIVE,  1,  0xFF,    0xF7,    NEXT)

	OPDEF(CEE_PREFIX6,                    "prefix6",          POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   1,  0xFF,    0xF9,    META)
	OPDEF(CEE_PREFIX5,                    "prefix5",          POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   1,  0xFF,    0xFA,    META)
	OPDEF(CEE_PREFIX4,                    "prefix4",          POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   1,  0xFF,    0xFB,    META)
	OPDEF(CEE_PREFIX3,                    "prefix3",          POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   1,  0xFF,    0xFC,    META)
	OPDEF(CEE_PREFIX2,                    "prefix2",          POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   1,  0xFF,    0xFD,    META)
	OPDEF(CEE_PREFIX1,                    "prefix1",          POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   1,  0xFF,    0xFE,    META)
	OPDEF(CEE_PREFIXREF,                  "prefixref",        POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   1,  0xFF,    0xFF,    META)

	OPDEF(CEE_ARGLIST,                    "arglist",          POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x00,    NEXT)
	OPDEF(CEE_CEQ,                        "ceq",              POP_1+POP_1,         PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x01,    NEXT)
	OPDEF(CEE_CGT,                        "cgt",              POP_1+POP_1,         PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x02,    NEXT)
	OPDEF(CEE_CGT_UN,                     "cgt.un",           POP_1+POP_1,         PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x03,    NEXT)
	OPDEF(CEE_CLT,                        "clt",              POP_1+POP_1,         PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x04,    NEXT)
	OPDEF(CEE_CLT_UN,                     "clt.un",           POP_1+POP_1,         PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x05,    NEXT)
	OPDEF(CEE_LDFTN,                      "ldftn",            POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_METHOD,       IPRIMITIVE,  2,  0xFE,    0x06,    NEXT)
	OPDEF(CEE_LDVIRTFTN,                  "ldvirtftn",        POP_REF,             PUSH_I,       OPERAND_PARAMS_INLINE_METHOD,       IPRIMITIVE,  2,  0xFE,    0x07,    NEXT)
	OPDEF(CEE_UNUSED56,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x08,    NEXT)
	OPDEF(CEE_LDARG,                      "ldarg",            POP_0,               PUSH_1,       OPERAND_PARAMS_INLINE_VAR,          IPRIMITIVE,  2,  0xFE,    0x09,    NEXT)
	OPDEF(CEE_LDARGA,                     "ldarga",           POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_VAR,          IPRIMITIVE,  2,  0xFE,    0x0A,    NEXT)
	OPDEF(CEE_STARG,                      "starg",            POP_1,               PUSH_0,       OPERAND_PARAMS_INLINE_VAR,          IPRIMITIVE,  2,  0xFE,    0x0B,    NEXT)
	OPDEF(CEE_LDLOC,                      "ldloc",            POP_0,               PUSH_1,       OPERAND_PARAMS_INLINE_VAR,          IPRIMITIVE,  2,  0xFE,    0x0C,    NEXT)
	OPDEF(CEE_LDLOCA,                     "ldloca",           POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_VAR,          IPRIMITIVE,  2,  0xFE,    0x0D,    NEXT)
	OPDEF(CEE_STLOC,                      "stloc",            POP_1,               PUSH_0,       OPERAND_PARAMS_INLINE_VAR,          IPRIMITIVE,  2,  0xFE,    0x0E,    NEXT)
	OPDEF(CEE_LOCALLOC,                   "localloc",         POP_I,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x0F,    NEXT)
	OPDEF(CEE_UNUSED57,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x10,    NEXT)
	OPDEF(CEE_ENDFILTER,                  "endfilter",        POP_I,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x11,    RETURN)
	OPDEF(CEE_UNALIGNED,                  "unaligned.",       POP_0,               PUSH_0,       OPERAND_PARAMS_SHORT_INLINE_I,       IPREFIX,     2,  0xFE,    0x12,    META)
	OPDEF(CEE_VOLATILE,                   "volatile.",        POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPREFIX,     2,  0xFE,    0x13,    META)
	OPDEF(CEE_TAILCALL,                   "tail.",            POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPREFIX,     2,  0xFE,    0x14,    META)
	OPDEF(CEE_INITOBJ,                    "initobj",          POP_I,               PUSH_0,       OPERAND_PARAMS_INLINE_TYPE,         IOBJMODEL,   2,  0xFE,    0x15,    NEXT)
	OPDEF(CEE_CONSTRAINED,                "constrained.",     POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_TYPE,         IPREFIX,     2,  0xFE,    0x16,    META)
	OPDEF(CEE_CPBLK,                      "cpblk",            POP_I+POP_I+POP_I,   PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x17,    NEXT)
	OPDEF(CEE_INITBLK,                    "initblk",          POP_I+POP_I+POP_I,   PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x18,    NEXT)
	OPDEF(CEE_UNUSED69,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x19,    NEXT)
	OPDEF(CEE_RETHROW,                    "rethrow",          POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IOBJMODEL,   2,  0xFE,    0x1A,    THROW)
	OPDEF(CEE_UNUSED51,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x1B,    NEXT)
	OPDEF(CEE_SIZEOF,                     "sizeof",           POP_0,               PUSH_I,       OPERAND_PARAMS_INLINE_TYPE,         IPRIMITIVE,  2,  0xFE,    0x1C,    NEXT)
	OPDEF(CEE_REFANYTYPE,                 "refanytype",       POP_1,               PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x1D,    NEXT)
	OPDEF(CEE_READONLY,                   "readonly.",        POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPREFIX,     2,  0xFE,    0x1E,    META)
	//Temporary instruction, need to be resolved
	OPDEF(CEE_LEAVE_TMP,                   "leave_tmp",	      POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x1F,    NEXT)
	OPDEF(CEE_UNUSED54,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x20,    NEXT)
	OPDEF(CEE_UNUSED55,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x21,    NEXT)
	OPDEF(CEE_UNUSED70,                   "unused",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x22,    NEXT)

	// These are not real opcodes, but they are handy internally in the EE
	OPDEF(CEE_EXT_LDARG,                 "ldarg_tmp",         POP_0,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   0,  0xFE,    0xF0,    META)
	OPDEF(CEE_EXT_STARG,                 "starg_tmp",         POP_1,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   0,  0xFE,    0xF1,    META)
	OPDEF(CEE_EXT_LDLOC,                 "ldloc_tmp",         POP_0,               PUSH_1,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   0,  0xFE,    0xF2,    META)
	OPDEF(CEE_EXT_STLOC,                 "stloc_tmp",         POP_1,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   0,  0xFE,    0xF3,    META)

	OPDEF(CEE_CODE_LABEL,                 "codelabel",        POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_VAR,          IINTERNAL,   0,  0xFE,    0xFD,    META)
	OPDEF(CEE_MACRO_END,                  "endmac",           POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   0,  0xFE,    0xFE,    META)
	OPDEF(CEE_ILLEGAL,                    "illegal",          POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   0,  0xFE,    0xFF,    META)

	// CRIScript expansion
	OPDEF(CEE_EXT_CNE,                    "cne_ext",          POP_1+POP_1,         PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x23,    NEXT)
	OPDEF(CEE_EXT_CGE,                    "cge_ext",          POP_1+POP_1,         PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x24,    NEXT)
	OPDEF(CEE_EXT_CLE,                    "cle_ext",          POP_1+POP_1,         PUSH_I,       OPERAND_PARAMS_INLINE_NONE,         IPRIMITIVE,  2,  0xFE,    0x25,    NEXT)
	OPDEF(CEE_FORCE_DWORD,                     NULL,          POP_0,               PUSH_0,       OPERAND_PARAMS_INLINE_NONE,         IINTERNAL,   0,  0,       0,       META)
};

/***************************************************************************
 *      Methods
 ***************************************************************************/

} //namespace CRI